services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/mediafiles
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./documents:/app/documents
      - ./config:/app/prompts
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/mediafiles
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION_NAME=regulations_final
      - QDRANT_VECTOR_SIZE=1024
      - RAG_TOP_K=5
      - TZ=Asia/Seoul
      - DEBUG=False
      - ALLOWED_HOSTS=growing.ai.kr,www.growing.ai.kr,api.growing.ai.kr
      - CSRF_TRUSTED_ORIGINS=https://growing.ai.kr,https://www.growing.ai.kr
    depends_on:
      - qdrant
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT}:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
      - ./qdrant_snapshots:/qdrant/snapshots
      - ./documents:/qdrant/documents
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__STORAGE__SNAPSHOTS_PATH=/qdrant/snapshots
    restart: unless-stopped


volumes:
  static_volume:
  media_volume:
  qdrant_storage:
 